#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: stylish
# File Options
files:
  include: 'src/scss/**/*.scss'
  ignore:
    - 'src/scss/base/_reset.scss'
    - 'src/scss/base/_fonts.scss'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  leading-zero: 2
  no-empty-rulesets: 2
  no-invalid-hex: 2
  no-trailing-whitespace: 1
  space-before-brace: 2
  # variable-name-format:
  #   - 2
  #   -
  #     convention: hyphenatedlowercase
  nesting-depth:
    - 2
    -
      max-depth: 3
  # class-name-format:
  #   - 2
  #   -
  #     convention: hyphenatedlowercase
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 0
  variable-for-property:
    - 0
  shorthand-values:
    - 1
  quotes:
    - 2
    -
      style: 'single'